# Generated by Django 4.2.1 on 2023-05-10 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_wallettransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='currency_currency',
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=13),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='destination',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='deposit', to='users.wallet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='source',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='transfer', to='users.wallet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(choices=[('ngn', 'NGN'), ('eur', 'EUR'), ('usd', 'USD')], default='NGN', max_length=4),
        ),
    ]
